apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pictogram-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
        - pictogram.example.com
      secretName: pictogram-tls
  rules:
    - host: pictogram.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pictogram-service
                port:
                  number: 80
