apiVersion: v1
kind: Service
metadata:
  name: pictogram-service
spec:
  type: LoadBalancer
  selector:
    app: pictogram
  ports:
    - port: 80          # service port
      protocol: TCP
      targetPort: 3000  # container port
