apiVersion: v1
kind: Service
metadata:
  name: pictogram-service
spec:
  type: NodePort
  selector:
    app: pictogram
  ports:
    - port: 80          # service port
      targetPort: 3000  # container port
      nodePort: 30001   # you'll access using <node-ip>:30001
